### ISSUE TITLE
Hide Certain Prop Variant

### ISSUE THREAD

**Issue by andrefox333** [blueberryapps/react-bluekit#68]
First of, awesome framework! We have chosen Bluekit to showcase our React components to all the developers that will be working on our app. Is there a way to hide certain prop variant from the UI? Let's say I have a propType `htmlFor` which either contains a string or not, and I would like to hide that from UI. 

Thanks in advance :)

**Comment by 12people** [comment]
@andrerecinto Thanks for the feedback! Could you explain why you'd like it hidden?

As the UX designer behind the project, I'd like to understand how people use it, so if you could find the time, I'd love to have a chat.

**Comment by andrerecinto** [comment]
No problem! We have certain props that doesn't have offer any visual representation change to the end user and we feel seeing a variant for it is unnecessary. Because whatever value you put in the prop, doesn't change the look and feel. So when you see the variant section for that specific prop it looks identical and can clutter up the preview screen when you have a lot of these variant prop views with the same output. 

I have a screen shot below that demonstrates that you don't see anything different with whatever value you put in the prop. I hope that make sense! :) Thanks again.


![screen shot 2016-09-30 at 9 56 38 am](https://cloud.githubusercontent.com/assets/5422172/18999813/4e77ed0c-86f4-11e6-83c2-1cdd81a2c0c4.png)

**Comment by imtoo** [comment]
That's a good point! We'll try to solve it in upcoming release next week. Thanks for your idea!

**Comment by andrerecinto** [comment]
Thanks so much :)

**Comment by ondrejbartas** [comment]
#75 this fixes your problem.
